AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: dist/src/lambda.handler
      Runtime: nodejs22.x

      Events:
        ExampleApi:
          Type: Api
          Properties:
            Path: /hello
            Method: get

  OrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: dist/src/orderLambda.handler
      Runtime: nodejs22.x
      
      Events:
        OrderApi:
          Type: Api
          Properties:
            Path: /order
            Method: post